### ISSUE TITLE
Core Func Dev Tracker

### ISSUE THREAD

**Issue by Gaukas** [Pie-Intl-Entmt/CloudVending#1]
### Core Functionalities Needed Before Implementing Main Features
- [x]  Database Func (At least 1 from below)
    - [x]  MySQL 
    - [ ]  PostgreSQL 
- [x]  Email Func (All of below)
    - [x]  Send with remote SMTP server
    - [x]  Recv with POP3/IMAP
- [x]  CAPTCHA Func (At least 2 from below)
    - [x] reCAPTCHA (Google)
    - [x] hCaptcha 
    - [ ] http://captchas.net/
- [x]  Templating (Jinja2)
- [x]  Blueprinting (Quart)

**Comment by Gaukas** [comment]
Minimum requirement met, now closing this issue.
